version: 2
updates:
  # npm依存関係の自動更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    reviewers:
      - "username" # 実際のGitHubユーザー名に置き換え
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # メジャーバージョンの更新は手動で行う
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    groups:
      # Playwright関連の依存関係をグループ化
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
      # ESLint関連の依存関係をグループ化
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
      # TypeScript関連の依存関係をグループ化
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
      # Testing Library関連の依存関係をグループ化
      testing-library:
        patterns:
          - "@testing-library/*"

  # GitHub Actions の自動更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"